### ISSUE TITLE
[BUG] If the TSC info is missing, the Linux kernel will attempt to use the PIT

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/boxy#48]
If the TSC info is missing, the Linux kernel will attempt to use the PIT instead of erroring out and telling the user that the TSC info is missing and that this hardware is not supported. A serial device should not be needed to get this information.

**Comment by chp-io** [comment]
This runtime error message requiring a serial device to be viewed is produced in PR #46 in [vclock.cpp#L302](https://github.com/Bareflank/boxy/blob/0ad62952e0410ae07088d2958fcf6b986ec7dea1/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp#L302).
More context on [gitter](https://gitter.im/Bareflank-hypervisor/Lobby?at=5e52c09b89f30b1265268ece).

**Comment by rianquinn** [comment]
So yeah, this code needs to report this information in some way that the Boxy VM can output a lack of support from userspace without the need for serial.

**Comment by chp-io** [comment]
In which header would make the most sense to export the [calibrate_tsc_freq_khz()](https://github.com/Bareflank/boxy/blob/0ad62952e0410ae07088d2958fcf6b986ec7dea1/bfvmm/src/hve/arch/intel_x64/virt/vclock.cpp#L247) function to be used by both bfexec and bfvmm?

I also tried implementing this fix by using vmcall which seemed at first like the "proper" way to do it but turns out to actually complicate things unnecessarily.
The problem with this approach is that every vcpu need to vmcall at initialization to set the tsc freq, including domU which defeats the purpose...

**Comment by rianquinn** [comment]
Huh... interesting question. Why not just move this to it's own header and implement it as a header only function that can be used to get this info?

**Comment by chp-io** [comment]
That makes perfect sense. Should it go under `bfsdk/include/bftsc.h` ?

**Comment by rianquinn** [comment]
for now, yeah that sounds like a solid place to put it.
